In [6]:
import numpy as np
import pandas as pd
import anndata as ad

In [ ]:
adata = ad.read_h5ad("data/janssens_2025_CellRanger_Velocyto_counts_eLNP.h5ad")

:

In [ ]:
orig_data = pd.read_csv("RNA_vs_ADT_corr_meanExpr.csv")
imputed_data = pd.read_csv("data/eLNPs_var>1.5_208_genes_RNA_history_imputed_protein.csv")

:

In [ ]:
imputed_data

       Bst2  Cd63  Cd9  Ilk  Itgb1  Lamp1  Lgals3  Procr  Sbno1  Sbno2  Vcam1
0        10   120   45    0     85     95     712      0      0      0      0
1         9   117   50    0     84     94     722      2      0      0      0
2        11   123   46    0     85     97     709      0      0      0      0
3        12   124    0    0     85     98     706      0      0      0      0
4        10   119   48    0     84     95     717      0      0      0      0
...     ...   ...  ...  ...    ...    ...     ...    ...    ...    ...    ...
21320    11   125    0    0     86     99     704      0      0      0      0
21321     8   115   45    0     86     94     726      2      0      0      0
21322     9   114   46    0     86     94     727      2      1      0      0
21323    25   256    0    0    173    303     439      0     17      0      0
21324     8   115   46    0     86     95     726      2      0      0      0

[21325 rows x 11 columns]

:

In [4]:
df_ADT = pd.read_csv("data/janssens_2025_preprint_author_ADT_counts_subset.csv", index_col=0)
df_RNA = pd.read_csv("data/janssens_2025_preprint_author_RNA_counts_subset.csv", index_col=0)

In [ ]:
# Subset cells

In [5]:
orig_data.loc[orig_data['Gene'].str.contains("Bst2")]

   Protein  Gene       Cor  Mean_RNA_expr
55   CD317  Bst2  0.170074       3.588037

In [14]:
imputed_data.index = df_ADT.index

ValueError: Length mismatch: Expected axis has 21325 elements, new values have 116588 elements

In [6]:
df_ADT[["CD317"]]

                      CD317
AAACCCAAGAAGCGGG-1_1      0
AAACCCAAGAATGTTG-1_1      0
AAACCCAAGAGCACTG-1_1      0
AAACCCAAGGGCAGTT-1_1      0
AAACCCACATAGCTGT-1_1      0
...                     ...
TTTGTTGCATCGAAGG-1_9      0
TTTGTTGGTTACACTG-1_9      0
TTTGTTGGTTTAAGGA-1_9      0
TTTGTTGTCATGGATC-1_9      0
TTTGTTGTCGTTGTTT-1_9      0

[116588 rows x 1 columns]

In [ ]:
imputed_data["Bst2"].corr(df_ADT["CD317"])

nan